services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      # Exclude node_modules from mount to use container's version
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - aidventure-network

  # Backend service (placeholder for future implementation)
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   env_file:
  #     - .env
  #   networks:
  #     - aidventure-network

networks:
  aidventure-network:
    driver: bridge
